---
- name: Dependency Installation
  hosts: all
  tasks:
    - name: Install Pip3
      apt:
        name: python3-pip
        state: present
        update_cache: yes
      become: yes
      become_user: root

- name: Directory Structure
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Ensure 'rpi' group is present
      group:
        name: rpi
        state: present
        gid: 7777
    - name: Ensure 'rpi' user is present
      user:
        name: rpi
        groups:
          - rpi
          - sudo
        state: present
        system: yes
        createhome: no
        uid: 7777