#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIR_ROOT="$( dirname "$( dirname "$( dirname "${DIR}")")")"
docker run -it --rm \
    -e ANSIBLE_HOST_KEY_CHECKING=False \
    -v "/${DIR_ROOT}/":/workspace:ro \
    --workdir //workspace \
    ansible/ansible-runner $@